name: build-docker-image
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build-docker-image:
    runs-on: ubuntu-22.04


    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        uses: ./.github/actions/docker
        with: 
          docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
          docker_hub_token: ${{ secrets.GITHUB_HUB_TOKEN }}
          image_name: fastapi-mongo-demo:latest

      
      # - name: docker login
      #   run: |
      #     echo $DOCKER_HUB_TOKEN > password.txt
      #     cat password.txt | docker login --username $DOCKER_HUB_USER --password-stdin
      # - name: build image
      #   run: |
      #     docker image build -t $DOCKER_HUB_USER/fastapi-demo:latest .
      # - name: push image
      #   run: |
      #     docker image push $DOCKER_HUB_USER/fastapi-demo:latest
