name: demo
on: 
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  test-code:
    # runs-on: ubuntu-22.04
    runs-on: ubuntu-22.04
    # strategy: 
    #   matrix:
    #     version: ['3.8', '3.9']
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up py
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run py test
        run: pytest
      - name: upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: htmlcov/
  
  deploy:
    runs-on: ubuntu-22.04
    if: success()

    needs: test-code
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: deploy code
        run: echo "deploy........."